import type { CoverLetterTemplateFamily, ResumeTemplateFamily, SubscriptionTier, TemplateTier } from "@prisma/client";
export type ResumeBasics = { fullName: string; professionalTitle: string; email: string; phone: string; location: string; website: string; linkedIn: string; photoUrl: string; };
export type ResumeExperienceItem = { id: string; role: string; company: string; location: string; startDate: string; endDate: string; bullets: string[]; };
export type ResumeEducationItem = { id: string; degree: string; school: string; location: string; startDate: string; endDate: string; details: string; };
export type ResumeData = { basics: ResumeBasics; summary: string; experience: ResumeExperienceItem[]; education: ResumeEducationItem[]; skills: string[]; projects: any[]; certifications: any[]; links: any[]; };
export type CoverLetterData = { jobTitle: string; company: string; hiringManager: string; intro: string; body: string; closing: string; };
export type TemplateKind = "resume" | "coverLetter";
export type LayoutMode = "single-column" | "two-column" | "header-accent";
export type ThemeConfig = { accent: string; accentSoft: string; surface: string; text: string; muted: string; };
export type TemplateMetadata = { key: string; name: string; description: string; previewLabel: string; kind: TemplateKind; tier: TemplateTier; };
export type ResumeTemplateConfig = { metadata: TemplateMetadata; family: RResumeTemplateFamily; layout: any; theme: ThemeConfig; visibleSections: Array<keyof ResumeData>; };
export type CoverLetterTemplateConfig = { metadata: TemplateMetadata; family: CoverLetterTemplateFamily; layout: any; theme: ThemeConfig; visibleSections: Array<keyof CoverLetterData>; };
export type BuilderPlanSnapshot = { tier: SubscriptionTier; label: string; features: any; };
